namespace: private-infra

resources:
- namespace.yaml
- public-static-ip-svc.yaml

helmCharts:
- name: ingress-nginx
  version: 4.2.1
  repo: https://kubernetes.github.io/ingress-nginx
  releaseName: ingress-nginx
  valuesInline:
    controller:
      replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 90Mi
      service:
        external:
          enabled: true  # true is the default

      publishService:
        enabled: true
        pathOverride: private-infra/public-static-ip
